# Generated by Django 5.0.3 on 2024-04-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_archtype_school_spell_discription_spell_arh_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charskill',
            name='char',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='news.charlist'),
        ),
        migrations.AlterField(
            model_name='charskill',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chars', to='news.skill'),
        ),
    ]
